### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by rosenb0rg** [JustusThies/NeuralVoicePuppetry#4]
When trying to run transfer.py with the sample datasets I get the following output:

```
----------------- Options ---------------
             aspect_ratio: 1.0                           
        audio_window_size: 16                            
               batch_size: 1                             
            cached_images: False                         
          checkpoints_dir: ./checkpoints                 
                 dataroot: ./datasets/                          [default: None]
             dataset_mode: face                                 [default: aligned]
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
            erosionFactor: 1.0                           
                     eval: False                         
                 fineSize: 512                           
             fix_renderer: False                         
                  gpu_ids: 0                             
          hierarchicalTex: False                         
                init_gain: 0.02                          
                init_type: xavier                        
                 input_nc: 3                             
                  isTrain: False                                [default: None]
                 loadSize: 512                           
                load_iter: 0                                    [default: 0]
               look_ahead: False                         
                 lossType: L1                            
         max_dataset_size: inf                           
                    model: audio2ExpressionsAttentionTMP4       [default: test]
               n_layers_D: 3                             
                     name: experiment_name               
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
          no_augmentation: False                         
               no_dropout: False                         
                     norm: instance                      
                    ntest: inf                           
                 num_test: 50                            
              num_threads: 4                             
 output_audio_expressions: False                         
                output_nc: 3                             
                    phase: test                          
                 renderer: no_renderer                   
             rendererType: UNET_5_level                  
           resize_or_crop: resize_and_crop               
              results_dir: ./results/                    
                  seq_len: 1                             
           serial_batches: False                         
             source_actor:                               
               source_dir: ./datasets/                   
                   suffix:                               
             target_actor:                               
                  tex_dim: 256                           
             tex_features: 16                            
tex_features_intermediate: 16                            
             textureModel: DynamicNeuralTextureAudio     
                  verbose: False                         
          write_no_images: False                         
----------------- End -------------------
#train objects = 116
>>> create model <<<
EstimatorType:  UNET_5_level
Traceback (most recent call last):
  File "transfer.py", line 85, in <module>
    model = load_model(opt)
  File "transfer.py", line 31, in load_model
    model = create_model(opt)
  File "/home/tom/local/NeuralVoicePuppetry/Audio2ExpressionNet/Inference/models/__init__.py", line 37, in create_model
    instance.initialize(opt)
  File "/home/tom/local/NeuralVoicePuppetry/Audio2ExpressionNet/Inference/models/audio2ExpressionsAttentionTMP4_model.py", line 197, in initialize
    self.netG = define_ExpressionEstimator(estimatorType=opt.rendererType, nIdentities=nIdentities, seq_len=opt.seq_len, gpu_ids=self.gpu_ids)
  File "/home/tom/local/NeuralVoicePuppetry/Audio2ExpressionNet/Inference/models/audio2ExpressionsAttentionTMP4_model.py", line 145, in define_ExpressionEstimator
    return networks.init_net(net, init_type, init_gain, gpu_ids)
  File "/home/tom/local/NeuralVoicePuppetry/Audio2ExpressionNet/Inference/models/networks.py", line 68, in init_net
    net.to(gpu_ids[0])
AttributeError: 'NoneType' object has no attribute 'to'
```

I am running 
pytorch 1.5.1  py3.7_cuda10.2.89_cudnn7.6.5_0
Any thoughts on the source of this error?

**Comment by rosenb0rg** [comment]
Resolved it by properly using the transfer.sh file. I had to run with with 'bash transfer.sh' I think because my default shell is zsh. Problem solved.
